# syntax=docker/dockerfile:1

# Build
FROM golang:1.16-buster AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY . .

RUN go build -o /chore-board

# Deploy
FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /chore-board /chore-board

EXPOSE 80

USER nonroot:nonroot

ENTRYPOINT ["/chore-board"]
