// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Chore struct {
	ID       int    `json:"id"`
	Text     string `json:"text"`
	Done     bool   `json:"done"`
	Image    string `json:"image"`
	Tutorial string `json:"tutorial"`
}

type User struct {
	ID      int    `json:"id"`
	Name    string `json:"name"`
	Email   string `json:"email"`
	Image   string `json:"image"`
	ChoreID int    `json:"choreId"`
	Admin   bool   `json:"admin"`
}
